server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/ridelink_account?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ride
    password: ride123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ridelink-super-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
    expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.ridelink.account_service: DEBUG